name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: terraform-fmt
    uses: hashicorp/terraform-github-actions/fmt@v0.4.0
    env:
      TF_ACTION_WORKING_DIR: .
      TF_ACTION_WORKSPACE: default
      TF_ACTION_COMMENT: "false"

