name: Start template validation

on: 
  push:
    branches:
    - master
    - f/*

jobs:
  build:
    name: Validate templates
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/terraform-github-actions/fmt@v0.4.0
        env:
          TF_ACTION_WORKING_DIR: .
          TF_ACTION_WORKSPACE: default
          TF_ACTION_COMMENT: "false"
      - uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          TF_ACTION_WORKING_DIR: .
          TF_ACTION_WORKSPACE: default
          TF_ACTION_COMMENT: "false"
      - uses: hashicorp/terraform-github-actions/validate@v0.4.0
        env:
          TF_ACTION_WORKING_DIR: .
          TF_ACTION_WORKSPACE: default
          TF_ACTION_COMMENT: "false"                 
